# Calculate MSD: $MSD \equiv \frac{1}{N}\sum\limits_{i=1}^{N} |x^{(i)}(t)-x^{(i)}(0)|^2$

## initialize data

In [6]:
import numpy as np
from numpy.linalg import norm

num_samples=5
dims=3
data=np.random.randn(num_samples, dims)
print(data)

[[-0.20542561 -2.04076302 -2.00395185]
 [ 0.64629111 -1.28586771  1.89857066]
 [ 0.12095833  0.41632214 -0.87963111]
 [ 0.54799319  0.86783849  0.23146293]
 [-1.18812619 -0.24477236 -0.90591114]]


In [9]:
def msd(data):
    x0=data[0]
    step1=norm(data-x0, axis=1)
    step2=step1**2
    return np.mean(step2)

print(msd(data))

8.670903868403931
