# This notebook is for strategies to build a co-occurrence matrix

# Imports

In [1]:
import torch
import numpy as np
from numpy.lib.stride_tricks import sliding_window_view

%load_ext autoreload
%autoreload 2
%matplotlib inline

# Set testing array and co-occurrence matrix

In [2]:
n = 10
a = np.arange(n).reshape((2, 5))

print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


# Get Co-occurrence pairs in torch

In [3]:

torch_pairs = torch.tensor(a).unfold(1, 2, 1)

print(torch_pairs)

tensor([[[0, 1],
         [1, 2],
         [2, 3],
         [3, 4]],

        [[5, 6],
         [6, 7],
         [7, 8],
         [8, 9]]])


# Get Co-occurrence pairs in numpy

In [9]:

np_pairs = sliding_window_view(a, (2,), axis=1)
np_pairs = np.vstack(np_pairs)
print(np_pairs)

[[0 1]
 [1 2]
 [2 3]
 [3 4]
 [5 6]
 [6 7]
 [7 8]
 [8 9]]
